-- AUTO-GENERATED from prod SQLite schema. Postgres dialect.
-- Regenerate: node scripts/translate-schema.cjs  (dev only)
CREATE EXTENSION IF NOT EXISTS citext;

-- ===== Tables =====
CREATE TABLE IF NOT EXISTS achievements (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_name  text    NOT NULL,
  badge_id     text    NOT NULL,
  unlocked_at  bigint NOT NULL,
  UNIQUE(player_name, badge_id)
);
CREATE TABLE IF NOT EXISTS adaptive_state (
  learner text NOT NULL,
  skill   text NOT NULL,
  p_known double precision NOT NULL DEFAULT 0.20,
  attempts bigint NOT NULL DEFAULT 0,
  correct_streak bigint NOT NULL DEFAULT 0,
  fail_streak bigint NOT NULL DEFAULT 0,
  last_at bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (learner, skill)
);
CREATE TABLE IF NOT EXISTS admin_db_audit (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint NOT NULL,
  username    text,
  sql         text    NOT NULL,
  changes     bigint,
  last_id     bigint,
  error       text,
  created_at  bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS ai_decisions (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id     bigint NOT NULL,
  decided_by     text    NOT NULL,
  model          text,
  action         text    NOT NULL,
  status_applied text,
  reason         text,
  public_note    text,
  priority_score bigint,
  confidence     double precision,
  input_snapshot text,
  raw_output     text,
  created_at     bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS ai_lesson_content (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_id     text    NOT NULL,
  subject     text,
  topic       text,
  kind        text    NOT NULL,
  stem        text,
  payload     text    NOT NULL,
  student     text,
  upvotes     bigint NOT NULL DEFAULT 0,
  flagged     bigint NOT NULL DEFAULT 0,
  created_at  bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS ai_prompt_log (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         bigint,
  role            text,
  endpoint        text    NOT NULL,
  prompt_text     text,
  blocked         bigint NOT NULL DEFAULT 0,
  block_reason    text,
  block_category  text,
  created_at      bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS ai_token_usage (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           bigint,
  provider          text    NOT NULL,
  model             text    NOT NULL,
  endpoint          text    NOT NULL,
  prompt_tokens     bigint NOT NULL DEFAULT 0,
  completion_tokens bigint NOT NULL DEFAULT 0,
  cost_usd_micros   bigint NOT NULL DEFAULT 0,
  duration_ms       bigint,
  status            text    NOT NULL,
  created_at        bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS analytics_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint,
  anon_id     text,
  name        text    NOT NULL,
  props       text,
  session_id  text,
  path        text,
  ts          bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS attempts (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version      text    NOT NULL,
  player_name  text    NOT NULL DEFAULT 'Ẩn danh',
  score        bigint NOT NULL,
  correct      bigint NOT NULL,
  total        bigint NOT NULL,
  duration_ms  bigint,
  details      text,
  created_at   bigint NOT NULL,
  class_code   text,
  level_n      bigint
);
CREATE TABLE IF NOT EXISTS bp_progress (
  user_id         bigint NOT NULL,
  season_id       bigint NOT NULL,
  season_xp       bigint NOT NULL DEFAULT 0,
  has_premium     bigint NOT NULL DEFAULT 0,
  claimed_free    text NOT NULL DEFAULT '[]',
  claimed_premium text NOT NULL DEFAULT '[]',
  updated_at      bigint NOT NULL,
  PRIMARY KEY (user_id, season_id)
);
CREATE TABLE IF NOT EXISTS bp_seasons (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            text NOT NULL UNIQUE,
  name            text NOT NULL,
  theme           text,
  started_at      bigint NOT NULL,
  ends_at         bigint NOT NULL,
  is_active       bigint NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS campus_layouts (
  domain      text    PRIMARY KEY,
  layout      text    NOT NULL,
  updated_at  bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS classes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          text    NOT NULL UNIQUE,
  name          text    NOT NULL,
  teacher_name  text    NOT NULL DEFAULT 'GV',
  created_at    bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS codelab_submissions (
  submission_id     text    NOT NULL,
  status            text    NOT NULL,
  problem_slug      text,
  external_user_ref text,
  user_id           bigint,
  score             double precision,
  passed_cases      bigint,
  total_cases       bigint,
  language_id       bigint,
  completed_at      bigint,
  processed_at      bigint NOT NULL,
  PRIMARY KEY (submission_id, status)
);
CREATE TABLE IF NOT EXISTS competencies (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        text    NOT NULL UNIQUE,
  kind        text    NOT NULL,
  name        text    NOT NULL,
  description text,
  sort_order  bigint NOT NULL DEFAULT 0,
  created_at  bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS content_datasets (
  collection  text NOT NULL,
  item_key    text NOT NULL,
  body        text NOT NULL,
  ord         bigint NOT NULL DEFAULT 0,
  source      text NOT NULL DEFAULT 'seed',
  active      bigint NOT NULL DEFAULT 1,
  updated_at  bigint NOT NULL,
  PRIMARY KEY (collection, item_key)
);
CREATE TABLE IF NOT EXISTS curriculum_content (
  id          text PRIMARY KEY,
  subject     text,
  year_level  bigint,
  semester    bigint,
  week        bigint,
  kind        text,
  title       text,
  body        text NOT NULL,
  source      text NOT NULL DEFAULT 'seed',
  active      bigint NOT NULL DEFAULT 1,
  updated_at  bigint NOT NULL,
  domain text,
  grade bigint
);
CREATE TABLE IF NOT EXISTS daily_login (
  user_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  streak          bigint NOT NULL DEFAULT 0,
  last_date       text NOT NULL DEFAULT '',
  total_claims    bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS engagement_daily_quests (
  user_id              bigint NOT NULL,
  quest_date           text    NOT NULL,
  slot                 bigint NOT NULL,
  kind                 text    NOT NULL,
  target               bigint NOT NULL,
  progress             bigint NOT NULL DEFAULT 0,
  claimed              bigint NOT NULL DEFAULT 0,
  reward_coin          bigint NOT NULL DEFAULT 0,
  reward_xp            bigint NOT NULL DEFAULT 0,
  label                text    NOT NULL DEFAULT '',
  PRIMARY KEY (user_id, quest_date, slot)
);
CREATE TABLE IF NOT EXISTS engagement_state (
  user_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  streak               bigint NOT NULL DEFAULT 0,
  longest_streak       bigint NOT NULL DEFAULT 0,
  last_active_date     text    NOT NULL DEFAULT '',
  hearts               bigint NOT NULL DEFAULT 5,
  hearts_refill_at     bigint NOT NULL DEFAULT 0,
  updated_at           bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS event_registry (
  name            text PRIMARY KEY,
  description     text,
  schema_json     text NOT NULL DEFAULT '{}',
  deprecated      bigint NOT NULL DEFAULT 0,
  added_at        bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS experiments (
  key             text PRIMARY KEY,
  status          text NOT NULL DEFAULT 'running',
  variants        text NOT NULL,
  description     text,
  started_at      bigint NOT NULL,
  ended_at        bigint
);
CREATE TABLE IF NOT EXISTS exposures (
  user_id         bigint NOT NULL,
  exp_key         text NOT NULL,
  variant         text NOT NULL,
  first_seen_at   bigint NOT NULL,
  seen_count      bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id, exp_key)
);
CREATE TABLE IF NOT EXISTS family_links (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_user_id  bigint NOT NULL,
  child_user_id   bigint NOT NULL,
  created_at      bigint NOT NULL,
  UNIQUE(parent_user_id, child_user_id)
);
CREATE TABLE IF NOT EXISTS feature_flags (
  key             text PRIMARY KEY,
  enabled         bigint NOT NULL DEFAULT 0,
  rollout_pct     double precision NOT NULL DEFAULT 100,
  description     text,
  updated_at      bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS league_groups (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id       bigint NOT NULL,
  tier            text    NOT NULL,
  seq             bigint NOT NULL,
  member_count    bigint NOT NULL DEFAULT 0,
  UNIQUE(season_id, tier, seq)
);
CREATE TABLE IF NOT EXISTS league_memberships (
  season_id       bigint NOT NULL,
  user_id         bigint NOT NULL,
  group_id        bigint NOT NULL,
  tier            text    NOT NULL,
  week_xp         bigint NOT NULL DEFAULT 0,
  final_rank      bigint,
  promoted        bigint DEFAULT 0,
  relegated       bigint DEFAULT 0,
  PRIMARY KEY (season_id, user_id)
);
CREATE TABLE IF NOT EXISTS league_seasons (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_start      text    NOT NULL UNIQUE,
  started_at      bigint NOT NULL,
  ended_at        bigint,
  created_at      bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS league_user_tier (
  user_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tier            text    NOT NULL DEFAULT 'bronze',
  updated_at      bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS learning_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  learner text NOT NULL,
  skill text NOT NULL,
  question_id text,
  correct bigint NOT NULL,
  duration_ms bigint,
  created_at bigint NOT NULL,
  domain text,
  context text
);
CREATE TABLE IF NOT EXISTS lesson_comments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       text NOT NULL,
  author     text,
  text       text NOT NULL,
  created_at bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS lesson_likes (
  slug       text NOT NULL,
  user_key   text NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY (slug, user_key)
);
CREATE TABLE IF NOT EXISTS lessons (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug         text NOT NULL UNIQUE,
  title        text NOT NULL,
  description  text,
  author       text,
  grade        text,
  subject      text,
  blocks_json  text NOT NULL,
  published    bigint NOT NULL DEFAULT 0,
  views        bigint NOT NULL DEFAULT 0,
  likes        bigint NOT NULL DEFAULT 0,
  created_at   bigint NOT NULL,
  updated_at   bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS live_rooms (
  pin           text PRIMARY KEY,
  host_id       bigint NOT NULL,
  title         text,
  questions     text NOT NULL,
  status        text NOT NULL DEFAULT 'lobby',
  created_at    bigint NOT NULL,
  ended_at      bigint
);
CREATE TABLE IF NOT EXISTS notif_config (
  k  text PRIMARY KEY,
  v  text NOT NULL
);
CREATE TABLE IF NOT EXISTS notif_subscriptions (
  user_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint     text,
  p256dh       text,
  auth         text,
  enabled      bigint NOT NULL DEFAULT 1,
  updated_at   bigint NOT NULL,
  last_push_at bigint
);
CREATE TABLE IF NOT EXISTS notifications (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_display_name text    NOT NULL,
  request_id        bigint,
  kind              text    NOT NULL,
  title             text    NOT NULL,
  body              text,
  url               text,
  read_at           bigint,
  created_at        bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS oauth_identities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint NOT NULL,
  provider    text    NOT NULL,
  subject     text    NOT NULL,
  email       text,
  created_at  bigint NOT NULL,
  UNIQUE(provider, subject)
);
CREATE TABLE IF NOT EXISTS outbox_events (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type      text    NOT NULL,
  payload         text    NOT NULL,
  endpoint_url    text    NOT NULL,
  endpoint_secret text    NOT NULL,
  status          text    NOT NULL DEFAULT 'pending',
  attempts        bigint NOT NULL DEFAULT 0,
  max_attempts    bigint NOT NULL DEFAULT 6,
  next_attempt_at bigint NOT NULL,
  last_error      text,
  created_at      bigint NOT NULL,
  updated_at      bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS portal_apps (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id      bigint NOT NULL,
  alias         text    NOT NULL,
  name          text    NOT NULL,
  description   text,
  icon          text,
  version       text,
  manifest_json text    NOT NULL,
  is_public     bigint NOT NULL DEFAULT 0,
  size_bytes    bigint NOT NULL DEFAULT 0,
  installed_at  bigint NOT NULL,
  updated_at    bigint NOT NULL,
  kind text NOT NULL DEFAULT 'embedded',
  target_url text,
  category text,
  domain text,
  UNIQUE(owner_id, alias)
);
-- PORTAL AGENTS — cài "Agent" kiểu AI Portal (assistant có base_url expose /metadata + /ask).
-- Khác portal_apps (frontend/tool): agent là dịch vụ LLM ngoài, Tizia chat-proxy tới base_url.
CREATE TABLE IF NOT EXISTS portal_agents (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id      bigint NOT NULL,
  alias         text   NOT NULL,
  name          text   NOT NULL,
  icon          text,
  base_url      text   NOT NULL,
  description   text,
  config_json   text,
  is_public     bigint NOT NULL DEFAULT 0,
  is_active     bigint NOT NULL DEFAULT 1,
  installed_at  bigint NOT NULL,
  updated_at    bigint NOT NULL,
  UNIQUE(owner_id, alias)
);
CREATE INDEX IF NOT EXISTS idx_portal_agents_owner ON portal_agents(owner_id);
CREATE INDEX IF NOT EXISTS idx_portal_agents_public ON portal_agents(is_public) WHERE is_public = 1;
CREATE TABLE IF NOT EXISTS question_attempts (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                bigint NOT NULL,
  scoreup_question_id    text,
  question_external_id   text,
  subject_id             text,
  chapter_id             text,
  answers_json           text,
  correct                bigint NOT NULL DEFAULT 0,
  score                  double precision    NOT NULL DEFAULT 0,
  duration_ms            bigint,
  created_at             bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS question_irt (
  question_id       text    PRIMARY KEY,
  subject_id        text,
  b                 double precision    NOT NULL DEFAULT 0,
  a                 double precision    NOT NULL DEFAULT 1,
  n_attempts        bigint NOT NULL DEFAULT 0,
  n_correct         bigint NOT NULL DEFAULT 0,
  updated_at        bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS request_messages (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id  bigint NOT NULL,
  role        text    NOT NULL,
  author_name text,
  body        text    NOT NULL,
  attachments text,
  created_at  bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS requests (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain      text    NOT NULL,
  type        text    NOT NULL DEFAULT 'other',
  title       text    NOT NULL,
  detail      text,
  student     text    NOT NULL DEFAULT 'Ẩn danh',
  status      text    NOT NULL DEFAULT 'pending',
  votes       bigint NOT NULL DEFAULT 1,
  admin_note  text,
  created_at  bigint NOT NULL,
  updated_at  bigint NOT NULL,
  attachments text
);
CREATE TABLE IF NOT EXISTS scenario_runs (
  user_id     bigint NOT NULL,
  family_id   text    NOT NULL,
  runs        bigint NOT NULL DEFAULT 0,
  best_stars  bigint NOT NULL DEFAULT 0,
  best_score  bigint NOT NULL DEFAULT 0,
  last_ts     bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, family_id)
);
CREATE TABLE IF NOT EXISTS school_admins (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      bigint NOT NULL,
  domain_id    text    NOT NULL,
  granted_at   bigint NOT NULL,
  granted_by   bigint,
  note         text,
  UNIQUE(user_id, domain_id)
);
CREATE TABLE IF NOT EXISTS scoreup_webhook_events_seen (
  event_id     text PRIMARY KEY,
  event_type   text,
  occurred_at  bigint,
  processed_at bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  token       text    PRIMARY KEY,
  user_id     bigint NOT NULL,
  created_at  bigint NOT NULL,
  expires_at  bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS shop_items (
  id              text PRIMARY KEY,
  type            text NOT NULL,
  name            text NOT NULL,
  description     text,
  price_coin      bigint NOT NULL,
  icon            text,
  payload         text,
  rarity          text NOT NULL DEFAULT 'common',
  available       bigint NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS skill_prereq (
  skill_id          bigint NOT NULL,
  prereq_skill_id   bigint NOT NULL,
  weight            double precision    NOT NULL DEFAULT 1.0,
  PRIMARY KEY (skill_id, prereq_skill_id)
);
CREATE TABLE IF NOT EXISTS skills (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code           text    NOT NULL UNIQUE,
  name           text    NOT NULL,
  competency_id  bigint NOT NULL,
  domain         text,
  grade_min      bigint,
  grade_max      bigint,
  description    text,
  created_at     bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS srs_card_content (
  card_key      text PRIMARY KEY,
  deck_id       bigint,
  front         text NOT NULL,
  back          text NOT NULL,
  hint          text,
  media_url     text,
  created_at    bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS srs_cards (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       bigint NOT NULL,
  card_key      text    NOT NULL,
  ease          double precision    NOT NULL DEFAULT 2.5,
  interval_d    double precision    NOT NULL DEFAULT 0,
  reps          bigint NOT NULL DEFAULT 0,
  lapses        bigint NOT NULL DEFAULT 0,
  total_reviews bigint NOT NULL DEFAULT 0,
  due_at        bigint NOT NULL,
  last_correct  bigint NOT NULL DEFAULT 0,
  last_seen     bigint NOT NULL,
  UNIQUE(user_id, card_key)
);
CREATE TABLE IF NOT EXISTS srs_decks (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id    bigint NOT NULL,
  name          text NOT NULL,
  description   text,
  subject_tag   text,
  grade_tag     text,
  is_public     bigint NOT NULL DEFAULT 1,
  created_at    bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS subscriptions (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           bigint NOT NULL,
  plan              text    NOT NULL DEFAULT 'free',
  status            text    NOT NULL DEFAULT 'active',
  seats             bigint NOT NULL DEFAULT 0,
  current_period_end bigint,
  order_ref         text,
  created_at        bigint NOT NULL,
  updated_at        bigint NOT NULL,
  UNIQUE(user_id)
);
CREATE TABLE IF NOT EXISTS team_quest_claims (
  team_quest_id   bigint NOT NULL,
  user_id         bigint NOT NULL,
  claimed_at      bigint NOT NULL,
  PRIMARY KEY (team_quest_id, user_id)
);
CREATE TABLE IF NOT EXISTS team_quest_contribs (
  team_quest_id   bigint NOT NULL,
  user_id         bigint NOT NULL,
  xp_contributed  bigint NOT NULL DEFAULT 0,
  last_at         bigint NOT NULL,
  PRIMARY KEY (team_quest_id, user_id)
);
CREATE TABLE IF NOT EXISTS team_quests (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_code      text NOT NULL,
  creator_id      bigint NOT NULL,
  title           text NOT NULL,
  description     text,
  target_xp       bigint NOT NULL,
  reward_coin     bigint NOT NULL DEFAULT 100,
  reward_xp       bigint NOT NULL DEFAULT 0,
  reward_item     text,
  starts_at       bigint NOT NULL,
  ends_at         bigint NOT NULL,
  status          text NOT NULL DEFAULT 'active',
  completed_at    bigint,
  created_at      bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS ugc_flags (
  user_id       bigint NOT NULL,
  quest_id      bigint NOT NULL,
  reason        text NOT NULL,
  flagged_at    bigint NOT NULL,
  PRIMARY KEY (user_id, quest_id)
);
CREATE TABLE IF NOT EXISTS ugc_likes (
  user_id       bigint NOT NULL,
  quest_id      bigint NOT NULL,
  PRIMARY KEY (user_id, quest_id)
);
CREATE TABLE IF NOT EXISTS ugc_plays (
  user_id       bigint NOT NULL,
  quest_id      bigint NOT NULL,
  score         bigint NOT NULL,
  played_at     bigint NOT NULL,
  PRIMARY KEY (user_id, quest_id, played_at)
);
CREATE TABLE IF NOT EXISTS ugc_quests (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id      bigint NOT NULL,
  title           text NOT NULL,
  description     text,
  subject_tag     text,
  grade_tag       text,
  questions       text NOT NULL,
  plays           bigint NOT NULL DEFAULT 0,
  likes           bigint NOT NULL DEFAULT 0,
  flags           bigint NOT NULL DEFAULT 0,
  status          text NOT NULL DEFAULT 'published',
  created_at      bigint NOT NULL,
  updated_at      bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS user_activity (
  user_id      bigint NOT NULL,
  at           bigint NOT NULL,
  kind         text NOT NULL DEFAULT 'visit',
  PRIMARY KEY (user_id, at)
);
CREATE TABLE IF NOT EXISTS user_domain_grants (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      bigint NOT NULL,
  domain_id    text    NOT NULL,
  granted_at   bigint NOT NULL,
  granted_by   bigint,
  expires_at   bigint,
  note         text,
  UNIQUE(user_id, domain_id)
);
CREATE TABLE IF NOT EXISTS user_inventory (
  user_id         bigint NOT NULL,
  item_id         text NOT NULL,
  acquired_at     bigint NOT NULL,
  equipped        bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, item_id)
);
CREATE TABLE IF NOT EXISTS user_pet (
  user_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id           text    NOT NULL,
  nickname         text,
  stage            bigint NOT NULL DEFAULT 0,
  xp               bigint NOT NULL DEFAULT 0,
  last_fed_at      bigint NOT NULL DEFAULT 0,
  created_at       bigint NOT NULL,
  updated_at       bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "user_skills" (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      bigint NOT NULL,
  skill_id     bigint NOT NULL,
  domain       text    NOT NULL DEFAULT '',
  earned_at    bigint NOT NULL,
  source_type  text,
  source_id    text,
  score        bigint,
  UNIQUE(user_id, skill_id, domain)
);
CREATE TABLE IF NOT EXISTS user_state (
  user_id    bigint NOT NULL,
  key        text    NOT NULL,
  value      text    NOT NULL DEFAULT '',
  updated_at bigint NOT NULL,
  PRIMARY KEY (user_id, key)
);
CREATE TABLE IF NOT EXISTS user_theta (
  user_id           bigint NOT NULL,
  subject_id        text    NOT NULL DEFAULT '',
  theta             double precision    NOT NULL DEFAULT 0,
  n_attempts        bigint NOT NULL DEFAULT 0,
  updated_at        bigint NOT NULL,
  PRIMARY KEY (user_id, subject_id)
);
CREATE TABLE IF NOT EXISTS "user_wallets" (
  user_id          bigint NOT NULL,
  domain           text    NOT NULL DEFAULT '',
  coins            bigint NOT NULL DEFAULT 0,
  xp               bigint NOT NULL DEFAULT 0,
  streak           bigint NOT NULL DEFAULT 0,
  longest_streak   bigint NOT NULL DEFAULT 0,
  streak_shields   bigint NOT NULL DEFAULT 0,
  last_visit_day   text    NOT NULL DEFAULT '',
  achievements     text    NOT NULL DEFAULT '[]',
  vr_sessions      bigint NOT NULL DEFAULT 0,
  meta_sessions    bigint NOT NULL DEFAULT 0,
  quizzes_passed   bigint NOT NULL DEFAULT 0,
  modules_by_day   text    NOT NULL DEFAULT '{}',
  daily            text    NOT NULL DEFAULT '{}',
  quests_claimed   text    NOT NULL DEFAULT '{}',
  updated_at       bigint NOT NULL,
  PRIMARY KEY (user_id, domain)
);
CREATE TABLE IF NOT EXISTS users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      citext    NOT NULL UNIQUE,
  display_name  text    NOT NULL,
  password_hash text    NOT NULL,
  role          text    NOT NULL DEFAULT 'student',
  created_at    bigint NOT NULL,
  last_login    bigint,
  email text,
  avatar_url text,
  age bigint,
  plan text NOT NULL DEFAULT 'free',
  plan_expires_at bigint,
  billing_cycle text,
  grade bigint,
  major text,
  cohort text,
  school_name text,
  enrolled_domain text
);
CREATE TABLE IF NOT EXISTS webhook_endpoints (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url         text    NOT NULL,
  secret      text    NOT NULL,
  event_types text,
  active      bigint NOT NULL DEFAULT 1,
  created_at  bigint NOT NULL
);

-- ===== Indexes =====
CREATE INDEX IF NOT EXISTS idx_ach_player ON achievements(player_name);
CREATE INDEX IF NOT EXISTS idx_adapt_skill ON adaptive_state(skill);
CREATE INDEX IF NOT EXISTS idx_admin_db_audit_user ON admin_db_audit(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_request ON ai_decisions(request_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_time    ON ai_decisions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_content_week
    ON ai_lesson_content(week_id, kind, flagged, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_log_blocked     ON ai_prompt_log(blocked, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_log_time        ON ai_prompt_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_log_user_time   ON ai_prompt_log(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_status      ON ai_token_usage(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_time        ON ai_token_usage(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_user_time   ON ai_token_usage(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ae_name_ts        ON analytics_events(name, ts);
CREATE INDEX IF NOT EXISTS idx_ae_ts             ON analytics_events(ts);
CREATE INDEX IF NOT EXISTS idx_ae_user_ts        ON analytics_events(user_id, ts);
CREATE INDEX IF NOT EXISTS idx_attempts_class ON attempts(class_code, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attempts_recent
    ON attempts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attempts_version_score
    ON attempts(version, score DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_classes_code ON classes(code);
CREATE INDEX IF NOT EXISTS idx_cls_ext_ref   ON codelab_submissions(external_user_ref, completed_at);
CREATE INDEX IF NOT EXISTS idx_cls_problem   ON codelab_submissions(problem_slug, status);
CREATE INDEX IF NOT EXISTS idx_cls_user      ON codelab_submissions(user_id, completed_at);
CREATE INDEX IF NOT EXISTS idx_content_ds_coll ON content_datasets(collection, active, ord);
CREATE INDEX IF NOT EXISTS idx_curriculum_active ON curriculum_content(active);
CREATE INDEX IF NOT EXISTS idx_curriculum_grade ON curriculum_content(domain, grade, active);
CREATE INDEX IF NOT EXISTS idx_curriculum_subject
    ON curriculum_content(subject, year_level, semester, week);
CREATE INDEX IF NOT EXISTS idx_engagement_dq_user_date
    ON engagement_daily_quests(user_id, quest_date);
CREATE INDEX IF NOT EXISTS idx_family_child  ON family_links(child_user_id);
CREATE INDEX IF NOT EXISTS idx_family_parent ON family_links(parent_user_id);
CREATE INDEX IF NOT EXISTS idx_league_mem_group_xp
    ON league_memberships(group_id, week_xp DESC);
CREATE INDEX IF NOT EXISTS idx_league_mem_user_season
    ON league_memberships(user_id, season_id);
CREATE INDEX IF NOT EXISTS idx_le_learner ON learning_events(learner);
CREATE INDEX IF NOT EXISTS idx_le_skill   ON learning_events(skill);
CREATE INDEX IF NOT EXISTS idx_lesson_comments_slug ON lesson_comments(slug, created_at);
CREATE INDEX IF NOT EXISTS idx_lessons_published ON lessons(published, created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_request
    ON notifications(request_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user
    ON notifications(user_display_name, read_at, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_oauth_user ON oauth_identities(user_id);
CREATE INDEX IF NOT EXISTS idx_outbox_due ON outbox_events(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_outbox_time ON outbox_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_portal_apps_kind_domain ON portal_apps(kind, domain);
CREATE INDEX IF NOT EXISTS idx_portal_apps_owner ON portal_apps(owner_id);
CREATE INDEX IF NOT EXISTS idx_portal_apps_public ON portal_apps(is_public) WHERE is_public = 1;
CREATE INDEX IF NOT EXISTS idx_qa_qid     ON question_attempts(scoreup_question_id);
CREATE INDEX IF NOT EXISTS idx_qa_subject ON question_attempts(subject_id, chapter_id);
CREATE INDEX IF NOT EXISTS idx_qa_user    ON question_attempts(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_request_messages
    ON request_messages(request_id, created_at);
CREATE INDEX IF NOT EXISTS idx_requests_domain ON requests(domain, votes DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scn_runs_user ON scenario_runs(user_id);
CREATE INDEX IF NOT EXISTS idx_school_admins_domain ON school_admins(domain_id);
CREATE INDEX IF NOT EXISTS idx_school_admins_user   ON school_admins(user_id);
CREATE INDEX IF NOT EXISTS idx_swes_processed ON scoreup_webhook_events_seen(processed_at);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_skill_prereq_child ON skill_prereq(skill_id);
CREATE INDEX IF NOT EXISTS idx_skills_competency ON skills(competency_id);
CREATE INDEX IF NOT EXISTS idx_skills_domain     ON skills(domain, grade_min, grade_max);
CREATE INDEX IF NOT EXISTS idx_srs_user_due ON srs_cards(user_id, due_at);
CREATE INDEX IF NOT EXISTS idx_srs_user_key ON srs_cards(user_id, card_key);
CREATE INDEX IF NOT EXISTS idx_subs_user ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_team_quests_class ON team_quests(class_code, status);
CREATE INDEX IF NOT EXISTS idx_ugc_creator ON ugc_quests(creator_id);
CREATE INDEX IF NOT EXISTS idx_ugc_subject ON ugc_quests(subject_tag, status);
CREATE INDEX IF NOT EXISTS idx_user_activity_user ON user_activity(user_id, at DESC);
CREATE INDEX IF NOT EXISTS idx_user_domain_grants_user ON user_domain_grants(user_id);
CREATE INDEX IF NOT EXISTS idx_user_skills_domain ON user_skills(user_id, domain, earned_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_skills_skill  ON user_skills(skill_id, earned_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_skills_user   ON user_skills(user_id, earned_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_state_user ON user_state(user_id);
CREATE INDEX IF NOT EXISTS idx_users_enrolled_domain ON users(enrolled_domain);
CREATE INDEX IF NOT EXISTS idx_users_plan ON users(plan, plan_expires_at);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_wh_active ON webhook_endpoints(active);

-- ===== Foreign keys (deferred so table order is irrelevant) =====
-- Wrapped: skip if already present.
DO $$ BEGIN
  BEGIN ALTER TABLE bp_progress ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE bp_progress ADD FOREIGN KEY (season_id) REFERENCES bp_seasons(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE daily_login ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE engagement_daily_quests ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE engagement_state ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE family_links ADD FOREIGN KEY (parent_user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE family_links ADD FOREIGN KEY (child_user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE league_groups ADD FOREIGN KEY (season_id) REFERENCES league_seasons(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE league_memberships ADD FOREIGN KEY (season_id) REFERENCES league_seasons(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE league_memberships ADD FOREIGN KEY (group_id) REFERENCES league_groups(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE league_memberships ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE league_user_tier ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE notif_subscriptions ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE oauth_identities ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE portal_apps ADD FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE question_attempts ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE scenario_runs ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE school_admins ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE school_admins ADD FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE sessions ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE skill_prereq ADD FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE skill_prereq ADD FOREIGN KEY (prereq_skill_id) REFERENCES skills(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE skills ADD FOREIGN KEY (competency_id) REFERENCES competencies(id) ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE srs_card_content ADD FOREIGN KEY (deck_id) REFERENCES srs_decks(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE srs_cards ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE srs_decks ADD FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE team_quest_contribs ADD FOREIGN KEY (team_quest_id) REFERENCES team_quests(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE team_quest_contribs ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE team_quests ADD FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE ugc_flags ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE ugc_flags ADD FOREIGN KEY (quest_id) REFERENCES ugc_quests(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE ugc_likes ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE ugc_likes ADD FOREIGN KEY (quest_id) REFERENCES ugc_quests(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE ugc_plays ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE ugc_plays ADD FOREIGN KEY (quest_id) REFERENCES ugc_quests(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE ugc_quests ADD FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_domain_grants ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_domain_grants ADD FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_inventory ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_inventory ADD FOREIGN KEY (item_id) REFERENCES shop_items(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_pet ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_skills ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_skills ADD FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_state ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_theta ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
  BEGIN ALTER TABLE user_wallets ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;
END $$;
