// Translate prod SQLite DDL (prod-schema.json) → Postgres schema.sql
const fs = require('fs');
const path = require('path');
const SC = __dirname;
const rows = JSON.parse(fs.readFileSync(path.join(SC, 'prod-schema.json'), 'utf8'));

// Split a comma-separated column/constraint list respecting parentheses.
function splitTop(s) {
  const out = []; let depth = 0, cur = '';
  for (const ch of s) {
    if (ch === '(') depth++;
    else if (ch === ')') depth--;
    if (ch === ',' && depth === 0) { out.push(cur); cur = ''; }
    else cur += ch;
  }
  if (cur.trim()) out.push(cur);
  return out;
}

function translateColumn(col) {
  let c = col.trim();
  // id INTEGER PRIMARY KEY AUTOINCREMENT  -> identity
  if (/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/i.test(c)) {
    return c.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/i,
      'bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  }
  // single-col INTEGER PRIMARY KEY (rowid alias) -> identity
  if (/\bINTEGER\s+PRIMARY\s+KEY\b/i.test(c)) {
    return c.replace(/\bINTEGER\s+PRIMARY\s+KEY\b/i,
      'bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  }
  // username ... COLLATE NOCASE -> citext (case-insensitive), drop COLLATE
  if (/COLLATE\s+NOCASE/i.test(c)) {
    c = c.replace(/\bTEXT\b/i, 'citext').replace(/\s*COLLATE\s+NOCASE/i, '');
    return c;
  }
  // generic type mapping
  c = c.replace(/\bINTEGER\b/gi, 'bigint')
       .replace(/\bREAL\b/gi, 'double precision')
       .replace(/\bTEXT\b/gi, 'text');
  return c;
}

const createStmts = [];
const fkStmts = [];
const tables = rows.filter(r => r.type === 'table');
const indexes = rows.filter(r => r.type === 'index');

for (const t of tables) {
  // Strip SQLite `-- ...` line comments (they contain commas that break splitTop).
  const sql = t.sql.replace(/--[^\n]*/g, '');
  const open = sql.indexOf('(');
  const close = sql.lastIndexOf(')');
  const head = sql.slice(0, open).replace(/CREATE TABLE/i, 'CREATE TABLE IF NOT EXISTS');
  const body = sql.slice(open + 1, close);
  const items = splitTop(body);
  const keep = [];
  for (const raw of items) {
    const item = raw.trim();
    if (!item) continue;
    if (/^FOREIGN\s+KEY/i.test(item)) {
      // Move FK to a deferred ALTER so table creation order doesn't matter.
      fkStmts.push(`ALTER TABLE ${t.name} ADD ${item.replace(/\s+/g, ' ')};`);
      continue;
    }
    if (/^(PRIMARY\s+KEY|UNIQUE|CHECK)\b/i.test(item)) { keep.push('  ' + item); continue; }
    keep.push('  ' + translateColumn(item));
  }
  createStmts.push(`${head}(\n${keep.join(',\n')}\n);`);
}

// Indexes: pass through, ensure IF NOT EXISTS present.
const idxStmts = indexes.map(i =>
  i.sql.replace(/CREATE\s+(UNIQUE\s+)?INDEX\s+(IF NOT EXISTS\s+)?/i,
    (m, uniq) => `CREATE ${uniq ? 'UNIQUE ' : ''}INDEX IF NOT EXISTS `) + ';'
);

const outSql = [
  '-- AUTO-GENERATED from prod SQLite schema. Postgres dialect.',
  '-- Regenerate: node scripts/translate-schema.cjs  (dev only)',
  'CREATE EXTENSION IF NOT EXISTS citext;',
  '',
  '-- ===== Tables =====',
  ...createStmts,
  '',
  '-- ===== Indexes =====',
  ...idxStmts,
  '',
  '-- ===== Foreign keys (deferred so table order is irrelevant) =====',
  '-- Wrapped: skip if already present.',
  'DO $$ BEGIN',
  ...fkStmts.map(s => '  BEGIN ' + s.replace(/;$/, '') + '; EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END;'),
  'END $$;',
  '',
].join('\n');

const outPath = path.join(SC, 'schema.sql');
fs.writeFileSync(outPath, outSql);
console.log('tables:', createStmts.length, 'indexes:', idxStmts.length, 'fks:', fkStmts.length);
console.log('written', outPath, fs.statSync(outPath).size, 'bytes');
