-- Tizia Postgres schema. Port từ SQLite (server/db.js cũ).
-- Quy ước:
--   * id: BIGINT GENERATED BY DEFAULT AS IDENTITY (≈ SQLite AUTOINCREMENT)
--   * timestamp epoch ms: BIGINT (giữ nguyên format cũ, caller không phải đổi Date.now())
--   * payload JSON: JSONB (query/index sau này dễ hơn TEXT)
--   * username case-insensitive: CITEXT (extension built-in từ PG 9.1)
--   * tenant: school_id INTEGER NOT NULL DEFAULT 1 (FK schools.id). school 1 = 'tizia-default'
--     chứa toàn bộ data legacy + single-tenant hiện tại. Multi-tenant Phase 1 chỉ cần
--     INSERT schools mới + ghi school_id đúng khi tạo user/attempt.
--
-- File này idempotent (CREATE IF NOT EXISTS / INSERT ... ON CONFLICT). Có thể chạy lại nhiều lần.

CREATE EXTENSION IF NOT EXISTS citext;

-- ── schools (tenant table) ──
CREATE TABLE IF NOT EXISTS schools (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  domain      TEXT,
  created_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_schools_code   ON schools(code);
CREATE INDEX IF NOT EXISTS idx_schools_domain ON schools(domain);

-- Seed default tenant (id=1, code='tizia-default') để legacy data có chỗ thuộc về.
INSERT INTO schools (id, code, name, created_at)
VALUES (1, 'tizia-default', 'Tizia', EXTRACT(EPOCH FROM NOW()) * 1000)
ON CONFLICT (id) DO NOTHING;

-- Đẩy sequence của id lên >= max(id) để INSERT mới không đụng id=1.
SELECT setval(
  pg_get_serial_sequence('schools', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM schools), 1),
  true
);

-- ── users ──
CREATE TABLE IF NOT EXISTS users (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username        CITEXT NOT NULL UNIQUE,
  display_name    TEXT NOT NULL,
  password_hash   TEXT NOT NULL,
  role            TEXT NOT NULL DEFAULT 'student',
  age             INTEGER,
  email           TEXT,
  avatar_url      TEXT,
  school_id       INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  created_at      BIGINT NOT NULL,
  last_login      BIGINT,
  grade           INTEGER,
  major           TEXT,
  cohort          TEXT,
  school_name     TEXT,
  plan            TEXT NOT NULL DEFAULT 'free',
  plan_expires_at BIGINT,
  billing_cycle   TEXT
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_school   ON users(school_id);
CREATE INDEX IF NOT EXISTS idx_users_plan     ON users(plan, plan_expires_at);

-- ── sessions ──
CREATE TABLE IF NOT EXISTS sessions (
  token       TEXT PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  BIGINT NOT NULL,
  expires_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user    ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

-- ── oauth_identities ──
CREATE TABLE IF NOT EXISTS oauth_identities (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider    TEXT NOT NULL,
  subject     TEXT NOT NULL,
  email       TEXT,
  created_at  BIGINT NOT NULL,
  UNIQUE (provider, subject)
);
CREATE INDEX IF NOT EXISTS idx_oauth_user ON oauth_identities(user_id);

-- ── classes ──
CREATE TABLE IF NOT EXISTS classes (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id     INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  code          TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL,
  teacher_name  TEXT NOT NULL DEFAULT 'GV',
  created_at    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_classes_code   ON classes(code);
CREATE INDEX IF NOT EXISTS idx_classes_school ON classes(school_id);

-- ── attempts ──
CREATE TABLE IF NOT EXISTS attempts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id    INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  version      TEXT NOT NULL,
  player_name  TEXT NOT NULL DEFAULT 'Ẩn danh',
  score        INTEGER NOT NULL,
  correct      INTEGER NOT NULL,
  total        INTEGER NOT NULL,
  duration_ms  INTEGER,
  details      JSONB,
  created_at   BIGINT NOT NULL,
  class_code   TEXT,
  level_n      INTEGER
);
CREATE INDEX IF NOT EXISTS idx_attempts_version_score ON attempts(version, score DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attempts_recent        ON attempts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attempts_class         ON attempts(class_code, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attempts_school        ON attempts(school_id, created_at DESC);

-- ── achievements ──
CREATE TABLE IF NOT EXISTS achievements (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_name  TEXT NOT NULL,
  badge_id     TEXT NOT NULL,
  unlocked_at  BIGINT NOT NULL,
  UNIQUE (player_name, badge_id)
);
CREATE INDEX IF NOT EXISTS idx_ach_player ON achievements(player_name);

-- ── requests (Ban điều hành AI inbox) ──
CREATE TABLE IF NOT EXISTS requests (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id   INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  domain      TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'other',
  title       TEXT NOT NULL,
  detail      TEXT,
  student     TEXT NOT NULL DEFAULT 'Ẩn danh',
  status      TEXT NOT NULL DEFAULT 'pending',
  votes       INTEGER NOT NULL DEFAULT 1,
  admin_note  TEXT,
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_requests_domain ON requests(domain, votes DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_requests_school ON requests(school_id, votes DESC, created_at DESC);

-- ── notifications ──
CREATE TABLE IF NOT EXISTS notifications (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id         INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  user_display_name TEXT NOT NULL,
  request_id        BIGINT,
  kind              TEXT NOT NULL,
  title             TEXT NOT NULL,
  body              TEXT,
  url               TEXT,
  read_at           BIGINT,
  created_at        BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_user    ON notifications(user_display_name, read_at, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_request ON notifications(request_id);

-- ── ai_lesson_content (kho học liệu AI sinh) ──
CREATE TABLE IF NOT EXISTS ai_lesson_content (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id   INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  week_id     TEXT NOT NULL,
  subject     TEXT,
  topic       TEXT,
  kind        TEXT NOT NULL,
  stem        TEXT,
  payload     JSONB NOT NULL,
  student     TEXT,
  upvotes     INTEGER NOT NULL DEFAULT 0,
  flagged     INTEGER NOT NULL DEFAULT 0,
  created_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_content_week ON ai_lesson_content(week_id, kind, flagged, created_at DESC);

-- ── family_links (Trục 4) ──
CREATE TABLE IF NOT EXISTS family_links (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  child_user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at      BIGINT NOT NULL,
  UNIQUE (parent_user_id, child_user_id)
);
CREATE INDEX IF NOT EXISTS idx_family_parent ON family_links(parent_user_id);
CREATE INDEX IF NOT EXISTS idx_family_child  ON family_links(child_user_id);

-- ── school_codes (redeem code do trường cấp) ──
CREATE TABLE IF NOT EXISTS school_codes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              CITEXT NOT NULL UNIQUE,
  school_id         INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  kind              TEXT NOT NULL DEFAULT 'grant_plan',
  grant_plan        TEXT,
  grant_days        INTEGER NOT NULL DEFAULT 365,
  discount_percent  INTEGER NOT NULL DEFAULT 0,
  max_uses          INTEGER NOT NULL DEFAULT 0,
  used_count        INTEGER NOT NULL DEFAULT 0,
  expires_at        BIGINT,
  note              TEXT,
  created_by        BIGINT,
  created_at        BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_school_codes_school ON school_codes(school_id, expires_at);

CREATE TABLE IF NOT EXISTS school_code_redemptions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_id      BIGINT NOT NULL REFERENCES school_codes(id) ON DELETE CASCADE,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  redeemed_at  BIGINT NOT NULL,
  outcome      TEXT,
  UNIQUE (code_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_redemption_user ON school_code_redemptions(user_id);

-- ── ai_token_usage + ai_prompt_log (ai-quota) ──
CREATE TABLE IF NOT EXISTS ai_token_usage (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id         INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  user_id           BIGINT,
  provider          TEXT NOT NULL,
  model             TEXT NOT NULL,
  endpoint          TEXT NOT NULL,
  prompt_tokens     INTEGER NOT NULL DEFAULT 0,
  completion_tokens INTEGER NOT NULL DEFAULT 0,
  cost_usd_micros   BIGINT NOT NULL DEFAULT 0,
  duration_ms       INTEGER,
  status            TEXT NOT NULL,
  created_at        BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_usage_school_time ON ai_token_usage(school_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_user_time   ON ai_token_usage(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_status      ON ai_token_usage(status, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_prompt_log (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id       INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  user_id         BIGINT,
  role            TEXT,
  endpoint        TEXT NOT NULL,
  prompt_text     TEXT,
  blocked         INTEGER NOT NULL DEFAULT 0,
  block_reason    TEXT,
  block_category  TEXT,
  created_at      BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_log_school_time ON ai_prompt_log(school_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_log_user_time   ON ai_prompt_log(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_log_blocked     ON ai_prompt_log(blocked, created_at DESC);

-- ── lessons + lesson_likes + lesson_comments ──
CREATE TABLE IF NOT EXISTS lessons (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug         TEXT NOT NULL UNIQUE,
  title        TEXT NOT NULL,
  description  TEXT,
  author       TEXT,
  grade        TEXT,
  subject      TEXT,
  blocks_json  JSONB NOT NULL,
  published    INTEGER NOT NULL DEFAULT 0,
  views        BIGINT NOT NULL DEFAULT 0,
  likes        BIGINT NOT NULL DEFAULT 0,
  created_at   BIGINT NOT NULL,
  updated_at   BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_lessons_published ON lessons(published, created_at);

CREATE TABLE IF NOT EXISTS lesson_likes (
  slug       TEXT NOT NULL,
  user_key   TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  PRIMARY KEY (slug, user_key)
);

CREATE TABLE IF NOT EXISTS lesson_comments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       TEXT NOT NULL,
  author     TEXT,
  text       TEXT NOT NULL,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_lesson_comments_slug ON lesson_comments(slug, created_at);

-- ── adaptive_state + learning_events ──
CREATE TABLE IF NOT EXISTS adaptive_state (
  learner        TEXT NOT NULL,
  skill          TEXT NOT NULL,
  p_known        DOUBLE PRECISION NOT NULL DEFAULT 0.20,
  attempts       INTEGER NOT NULL DEFAULT 0,
  correct_streak INTEGER NOT NULL DEFAULT 0,
  fail_streak    INTEGER NOT NULL DEFAULT 0,
  last_at        BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (learner, skill)
);
CREATE INDEX IF NOT EXISTS idx_adapt_skill ON adaptive_state(skill);

CREATE TABLE IF NOT EXISTS learning_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  learner     TEXT NOT NULL,
  skill       TEXT NOT NULL,
  question_id TEXT,
  correct     INTEGER NOT NULL,
  duration_ms INTEGER,
  created_at  BIGINT NOT NULL,
  domain      TEXT,
  context     TEXT
);
CREATE INDEX IF NOT EXISTS idx_le_learner ON learning_events(learner);
CREATE INDEX IF NOT EXISTS idx_le_skill   ON learning_events(skill);

-- ── payment: invoices + payments + refunds + ledger + webhook_inbox ──
CREATE TABLE IF NOT EXISTS invoices (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id   INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  user_id     BIGINT,
  order_ref   TEXT NOT NULL UNIQUE,
  amount      BIGINT NOT NULL,
  currency    TEXT NOT NULL DEFAULT 'VND',
  description TEXT,
  status      TEXT NOT NULL DEFAULT 'pending',
  gateway     TEXT,
  metadata    JSONB,
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT NOT NULL,
  paid_at     BIGINT
);
CREATE INDEX IF NOT EXISTS idx_invoices_order  ON invoices(order_ref);
CREATE INDEX IF NOT EXISTS idx_invoices_school ON invoices(school_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status, created_at DESC);

CREATE TABLE IF NOT EXISTS payments (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id        INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  invoice_id       BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  gateway          TEXT NOT NULL,
  gateway_txn_ref  TEXT,
  amount           BIGINT NOT NULL,
  status           TEXT NOT NULL,
  response_code    TEXT,
  raw_response     JSONB,
  created_at       BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_payments_invoice ON payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_school  ON payments(school_id, created_at DESC);

CREATE TABLE IF NOT EXISTS refunds (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id          INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  payment_id         BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  amount             BIGINT NOT NULL,
  reason             TEXT,
  status             TEXT NOT NULL DEFAULT 'pending',
  gateway_refund_ref TEXT,
  created_at         BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_refunds_payment ON refunds(payment_id);

CREATE TABLE IF NOT EXISTS ledger_entries (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id     INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  txn_group     TEXT NOT NULL,
  account       TEXT NOT NULL,
  amount_signed BIGINT NOT NULL,
  currency      TEXT NOT NULL DEFAULT 'VND',
  ref_type      TEXT,
  ref_id        BIGINT,
  memo          TEXT,
  created_at    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ledger_group   ON ledger_entries(txn_group);
CREATE INDEX IF NOT EXISTS idx_ledger_account ON ledger_entries(account, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_school  ON ledger_entries(school_id, created_at DESC);

CREATE TABLE IF NOT EXISTS webhook_inbox (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gateway         TEXT NOT NULL,
  event_key       TEXT NOT NULL,
  order_ref       TEXT,
  payload         JSONB,
  signature_valid INTEGER NOT NULL DEFAULT 0,
  processed       INTEGER NOT NULL DEFAULT 0,
  received_at     BIGINT NOT NULL,
  processed_at    BIGINT,
  UNIQUE (gateway, event_key)
);
CREATE INDEX IF NOT EXISTS idx_webhook_order ON webhook_inbox(order_ref);

-- ── campus_layouts ──
CREATE TABLE IF NOT EXISTS campus_layouts (
  domain      TEXT PRIMARY KEY,
  layout      JSONB NOT NULL,
  updated_at  BIGINT NOT NULL
);

-- ── webhook_endpoints + outbox_events (integration) ──
CREATE TABLE IF NOT EXISTS webhook_endpoints (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id   INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  url         TEXT NOT NULL,
  secret      TEXT NOT NULL,
  event_types TEXT,
  active      INTEGER NOT NULL DEFAULT 1,
  created_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_wh_school ON webhook_endpoints(school_id, active);

CREATE TABLE IF NOT EXISTS outbox_events (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id       INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  event_type      TEXT NOT NULL,
  payload         JSONB NOT NULL,
  endpoint_url    TEXT NOT NULL,
  endpoint_secret TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending',
  attempts        INTEGER NOT NULL DEFAULT 0,
  max_attempts    INTEGER NOT NULL DEFAULT 6,
  next_attempt_at BIGINT NOT NULL,
  last_error      TEXT,
  created_at      BIGINT NOT NULL,
  updated_at      BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_outbox_due    ON outbox_events(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_outbox_school ON outbox_events(school_id, created_at DESC);

-- ── subscriptions (billing) ──
CREATE TABLE IF NOT EXISTS subscriptions (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id          INTEGER NOT NULL REFERENCES schools(id) ON DELETE RESTRICT,
  plan               TEXT NOT NULL DEFAULT 'free',
  status             TEXT NOT NULL DEFAULT 'active',
  seats              INTEGER NOT NULL DEFAULT 0,
  current_period_end BIGINT,
  order_ref          TEXT,
  created_at         BIGINT NOT NULL,
  updated_at         BIGINT NOT NULL,
  UNIQUE (school_id)
);
CREATE INDEX IF NOT EXISTS idx_subs_school ON subscriptions(school_id);

-- ── analytics_events ──
CREATE TABLE IF NOT EXISTS analytics_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id   INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  user_id     BIGINT,
  anon_id     TEXT,
  name        TEXT NOT NULL,
  props       JSONB,
  session_id  TEXT,
  path        TEXT,
  ts          BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ae_school_name_ts ON analytics_events(school_id, name, ts);
CREATE INDEX IF NOT EXISTS idx_ae_user_ts        ON analytics_events(user_id, ts);
CREATE INDEX IF NOT EXISTS idx_ae_ts             ON analytics_events(ts);

-- ── ai_decisions ──
CREATE TABLE IF NOT EXISTS ai_decisions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id      INTEGER NOT NULL DEFAULT 1 REFERENCES schools(id) ON DELETE RESTRICT,
  request_id     BIGINT NOT NULL,
  decided_by     TEXT NOT NULL,
  model          TEXT,
  action         TEXT NOT NULL,
  status_applied TEXT,
  reason         TEXT,
  public_note    TEXT,
  priority_score INTEGER,
  confidence     DOUBLE PRECISION,
  input_snapshot JSONB,
  raw_output     TEXT,
  created_at     BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_request ON ai_decisions(request_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_decisions_school  ON ai_decisions(school_id, created_at DESC);

-- ── user_wallets (XP/coin/streak per-user) ──
-- JSON fields (achievements, modules_by_day, daily, quests_claimed) là JSONB —
-- pg driver tự convert object JS → JSONB và ngược lại, không cần JSON.parse/stringify.
CREATE TABLE IF NOT EXISTS user_wallets (
  user_id          BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  coins            BIGINT NOT NULL DEFAULT 0,
  xp               BIGINT NOT NULL DEFAULT 0,
  streak           INTEGER NOT NULL DEFAULT 0,
  longest_streak   INTEGER NOT NULL DEFAULT 0,
  streak_shields   INTEGER NOT NULL DEFAULT 0,
  last_visit_day   TEXT NOT NULL DEFAULT '',
  achievements     JSONB NOT NULL DEFAULT '[]'::jsonb,
  vr_sessions      INTEGER NOT NULL DEFAULT 0,
  meta_sessions    INTEGER NOT NULL DEFAULT 0,
  quizzes_passed   INTEGER NOT NULL DEFAULT 0,
  modules_by_day   JSONB NOT NULL DEFAULT '{}'::jsonb,
  daily            JSONB NOT NULL DEFAULT '{}'::jsonb,
  quests_claimed   JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at       BIGINT NOT NULL
);
